[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "nic"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
]

[tool.setuptools.packages.find]
where = [
    "src"
]
